### ISSUE TITLE
Hippocampe behind a proxy

### ISSUE THREAD

**Issue by robertnixon2003** [TheHive-Project/Hippocampe#52]
### Request Type
Bug

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04
| OS version (client)       | Windows 7
| Hippocampe version / git hash   | cf46107d6b586de01edc10e8334b60c51eb16a1b
| Package Type              | From source

### Problem Description
Shadowbook is failing due to corporate proxy. It does not use the set environment variables. Also states that a job is already running all the time even after the data is deleted and feeds re-indexed.

**Comment by robertnixon2003** [comment]
Since no one wanted to comment on this I will close it. I have came up with a solution but it involves modifying a shadowbook script. This is the modified downloader.py script. Bold sections are the modified versions. This could probably be done with a conf file and would be a better fit for those that do not have proxies. But this works. 



#!/usr/bin/env python
# -*- coding: utf8 -*-

import requests
from copy import deepcopy

**proxies = {
  'http': 'http://10.202.1.43:8080',
  'https': 'http://10.202.1.43:8080',
}**

def simpleDownload(url, listSessions):
        #listSessions is a list with authenticated sessions for feed which need to be authenticate

        #Before retrieving feed's data, we have to determine which session to use
        #by using listSessions[1:] we do not choose the first element which is the default session
        #in case that the top_level_url contains 'default'
        for session in listSessions[1:]:
                if session['sessionName'] in url:
                        selectedSession = deepcopy(session)
                else:
                        #the default session is always the first element in the list
                        selectedSession = listSessions[0]

        raw_page = selectedSession['session'].get(url, **proxies=proxies**, stream = True)
        #requests does not raise exception if status is not 200 by default
        #that's why we use raise_for_status()
        raw_page.raise_for_status()
        #returning raw content and not text to avoid encoding issues
        return raw_page.content

class EmptyFeedException(Exception):
        def __init__(self,url):
                Exception.__init__(self, 'Feed {0} is empty'.format(url))
                self.url = url


if __name__ == '__main__':
        main()

**Comment by mgabriel-silva** [comment]
And almost 2 years later, I'm having the same problem

I think this should be reopened to put proxy settings in the config
