### ISSUE TITLE
Job blocked on going"

### ISSUE THREAD

**Issue by FafnerKeyZee** [TheHive-Project/Hippocampe#54]
### Request Type
Bug 
### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64
|git hash   | commit f4d8807651eb44ad810c9697be0bb169e5402665
| Package Type              |  From source

### Problem Description
Job blocked "ongoing" 

### Steps to Reproduce
Install Hippocampe
run shadowbook
Retrieve feeds automatically and periodically
Wait few update until one task stays blocked

### Possible Solutions
N/A

### Complementary information
From command: curl -GET http://localhost:5000/hippocampe/api/v1.0/jobs
=>
  "AWFJifRJDaFPKWQ1ZZhx": {
    "startTime": "20180131T010713+0100", 
    "status": "ongoing"
  }

**Comment by ninSmith** [comment]
Hey,

Could you try the following:

```
curl http://localhost:9200/hippocampe/jobs/_delete_by_query -d '{
    "query": {
        "match_all": {}
    }
}’
```

Basically it erases all jobs, including the blocking ongoing one. After that, try to run shadowbook again.

**Comment by FafnerKeyZee** [comment]
Hey,

Thanks it did the job :)

BR,
